### ISSUE TITLE
Unable to create from output of asStructuredData()

### ISSUE THREAD

**Issue by mpresland** [spatie/opening-hours#154]
Hi,

I am testing this package for use in a project, however I can't seem to create from the output of `asStructuredData()`. The goal is to be able to store this in the DB, as I have 100+ "clients" each with multiple departments, with their own operating hours.

```
use Spatie\OpeningHours\OpeningHours;

$openingHours = OpeningHours::create([
    'monday'     => ['09:00-12:00', '13:00-18:00'],
]);

$opHours = OpeningHours::create($openingHours->asStructuredData());
```

Results in:
```Spatie/OpeningHours/Exceptions/InvalidDayName with message 'Day `0` isn't a valid day name. Valid day names are lowercase english words, e.g. `monday`, `thursday`.'```

PHP: 7.4
Laravel: 8.0.1

Any help would be great, as this package would simplify much of my current project.

**Comment by kylekatarnls** [comment]
Hello,

You don't need any `OpeningHours` method for that.

`->asStructuredData()` is made for SEO structured data (which makes search engines display the opening hours they found on your page in the search results).

How to save to and load from database has been addressed here (both the easy bulk way, and the precise way with joined tables):
https://github.com/spatie/opening-hours/issues/147#issuecomment-671204393
(actually the answer for this issue is the same with or without Eloquent)

We do not have dedicated tool because `OpeningHours` has actually no state, so you don't need to save it, you can simply save the array you used to create it.

Thanks,
