### ISSUE TITLE
Parsing store hours from arbitrary strings

### ISSUE THREAD

**Issue by tgraupne** [spatie/opening-hours#170]
Hi,

I'd like to respectfully ask if this library has the possibility to parse strings containing store hour information and create store hour objects on the fly?

I'd like to work with examples like this:

`"MO: 7:00 - 12:00 and 13:00 - 20:00, TUE: 6:00 - 20:00..."`

I hope I did not miss references in the README.

Cheers, Tom

**Comment by kylekatarnls** [comment]
Hi 👋 

We don't have. I could accept a pull-request for that if it would generic enough (making possible to define the separators, day format) because else, this would be way too custom to be widely useful.

Else, you're not blocked by the library for this, as it's quite easy to build the configuration array for oepning-hours using [`explode()`](https://www.php.net/manual/en/function.explode.php) in your string:
```php
$weekString = "MO: 7:00 - 12:00 and 13:00 - 20:00, TUE: 6:00 - 20:00...";
$hours = [];
$dayNames = [
  'MO' => 'monday',
  'TUE' => 'tuesday',
  ...
];

foreach (explode(',', $string) as $dayString) {
  [$dayCode, $hoursString] = explode(':', trim($dayString));
  $day = $dayNames[$dayCode];
  $hours[$day] = [];

  foreach (explode(' and ', $hoursString) as $range) {
    $hours[$day][] = str_replace(' ', '', $range);
  }
}

var_dump($hours);
```

**Comment by tgraupne** [comment]
Hi @kylekatarnls, thank you very much for your feedback.
Best, Tom
