### ISSUE TITLE
Fetching Opening Hours using asStructuredData() does not consider the passed Timezone

### ISSUE THREAD

**Issue by hazem-taha** [spatie/opening-hours#185]
Hello,

As mentioned, I have opening hours saved in the database as an array, when passing them to the `asStructuredData('H:i A', 'America/New_York')` for example, it does not consider the timezone changing and the hours are still the same as the database which is UTC based.

What is the correct way to print a list of opening hours for all week days considering the current user's `timezone` ESPECIALLY considering the overflowing times?

Is the below modification to the `asStructuredData` function correct ?

```php
public function asStructuredData(string $format = 'H:i', $timezone = null): array
    {
        $regularHours = $this->flatMap(function (OpeningHoursForDay $openingHoursForDay, string $day) use ($format, $timezone) {
            return $openingHoursForDay->map(function (TimeRange $timeRange) use ($format, $timezone, $day) {
                return [
                    '@type' => 'OpeningHoursSpecification',
                    'dayOfWeek' => Carbon::parse($day . ' ' . $timeRange->start()->format())->setTimezone($timezone)->format('l'),
                    'opens' => Carbon::parse($day . ' ' . $timeRange->start()->format())->setTimezone($timezone)->format($format),
                    'closes' => Carbon::parse($day . ' ' . $timeRange->end()->format())->setTimezone($timezone)->format($format),
                ];
            });
        });

        $exceptions = $this->flatMapExceptions(function (OpeningHoursForDay $openingHoursForDay, string $date) use ($format, $timezone) {
            if ($openingHoursForDay->isEmpty()) {
                $zero = Time::fromString('00:00')->format($format, $timezone);

                return [[
                    '@type' => 'OpeningHoursSpecification',
                    'opens' => $zero,
                    'closes' => $zero,
                    'validFrom' => $date,
                    'validThrough' => $date,
                ]];
            }

            return $openingHoursForDay->map(function (TimeRange $timeRange) use ($format, $date, $timezone) {
                return [
                    '@type' => 'OpeningHoursSpecification',
                    'opens' => Carbon::parse($date . ' ' . $timeRange->start()->format())->setTimezone($timezone)->format($format),
                    'closes' => Carbon::parse($date . ' ' . $timeRange->end()->format())->setTimezone($timezone)->format($format),
                    'validFrom' => $date,
                    'validThrough' => $date,
                ];
            });
        });

        return array_merge($regularHours, $exceptions);
    }
```

spatie/opening-hours package Version: `2.11.0`
Laravel Version: `8.70.2`
PHP Version: `8.0.13`

Thanks in advance.

**Comment by kylekatarnls** [comment]
Hello,

I don't think we can solve this just by modifying `asStructuredData()`, the `$timezone` parameter of this function is to specify the current timezone of the contained date and times (the input) and so it can appears accordingly if specified in the `$format` but not meant to convert anything for the output.

Conversion of a `OpeningHours` object from one timezone to an other is simply not possible as it does not fit in a single week representation. For instance Paris and New York have DST (daylight saving time) changes occurring on different dates and most timezones does not even have DST changes.

So the definition of opening hours for a typical week in New York would need 2 definitions once represented in UTC (one for winter, one for summer) and to be represented in Paris timezone, it would need 4 definitions, 2 for periods in summer and winter when both timezones are in sync and 2 for the few weeks where they're not in sync. Then you would need to check given date-time in user timezone, pick the right definition for the period, and only there you could print a list (which would be valid for current date but could change on next DST change).

Then we can't neither simply apply for each day the timezone to change the time, because `Monday 20:00-22:00` in New York is `Tuesday 05:00-07:00` in Tokyo. So when switching a range from a timezone to an other, it can end to a range overlapping with the day before, the day after, or a range completely on the day before/after. And since the possible offsets are between -12 and +14, the gap can even be 2 days.

So a conversion of the week representation requires to rebuild completely the data.

I suggestion the following process for this:
```php
use Spatie\OpeningHours\OpeningHours;

$inputTimezone = 'UTC';
$outputTimezone = 'America/New_York';

$inputData = [
    'monday'     => ['09:00-12:00', '13:00-18:00'],
    'tuesday'    => ['09:00-12:00', '13:00-18:00'],
    'wednesday'  => ['09:00-12:00'],
    'thursday'   => ['09:00-12:00', '13:00-18:00'],
    'friday'     => ['09:00-12:00', '13:00-20:00'],
    'saturday'   => ['09:00-12:00', '13:00-16:00'],
    'sunday'     => [],
];

$openingHoursForInputTimezone = OpeningHours::create($inputData);

$outputNow = CarbonImmutable::now($outputTimezone);

echo "Now it's $outputNow in $outputTimezone\n";

$inputNow = CarbonImmutable::now($inputTimezone);

echo "Now it's $inputNow in $inputTimezone\n";
echo "\n";
echo "Next week in $outputTimezone, opening hours will be:\n";

$weekStart = $outputNow->next('Monday');

$outputData = [];

foreach ($weekStart->toPeriod(7) as $date) {
  $key = strtolower($date->dayName);
  $outputData[$key] = [];
  $closingDate = $date;

  if ($openingHoursForInputTimezone->isOpenAt($date->tz($inputTimezone))) {
    $closingDate = $openingHoursForInputTimezone->nextClose($date->tz($inputTimezone))->tz($outputTimezone);

    if (!$closingDate->isSameDay($date)) {
      $outputData[$key][] = '00:00-24:00';
      
      continue;
    }

    $outputData[$key][] = '00:00-' . $closingDate->format('H:i');
  }

  while (true) {
    $nextOpen = $openingHoursForInputTimezone->nextOpen($closingDate->tz($inputTimezone))->tz($outputTimezone);

    if (!$nextOpen->isSameDay($date)) {
      continue 2;
    }

    $closingDate = $openingHoursForInputTimezone->nextClose($nextOpen->tz($inputTimezone))->tz($outputTimezone);

    if (!$closingDate->isSameDay($date)) {
      $outputData[$key][] = $nextOpen->format('H:i') . '-24:00';

      continue 2;
    }

    $outputData[$key][] = $nextOpen->format('H:i') . '-' . $closingDate->format('H:i');
  }
}

print_r($outputData);
```
Here you can replace `$inputData` obviously and the timezone with anything:
```php
$inputTimezone = 'America/New_York';
$outputTimezone = 'Asia/Tokyo';
```
For instance of `$inputData` contains New York times and the user is in Tokyo.
