### ISSUE TITLE
[Bug] nextOpen calculates the wrong date for a regular day with exceptions

### ISSUE THREAD

**Issue by c33s** [spatie/opening-hours#193]
having a monday open from 09:00-12:00 and additional having an exceptions on a monday from 13:00-18:00 let me assume that if i am on sunday `nextOpen` will result in 09:00 but it results in 13:00.

```php
        $now = new Carbon('2022-07-17 14:01'); // sunday
        Carbon::setTestNow($now);
        CarbonImmutable::setTestNow($now);
        $openingHours = new OpeningHours();
        $data = [
            'monday' => ['09:00-12:00'],
            'exceptions' => [
                '2022-07-18' => [
                    'hours' => ['13:00-18:00'], // monday
                ],
            ],
        ];

        $openingHours->fill($data);
        $actual = $openingHours->nextOpen($now)->format('Y-m-d H:i');
        $this->assertEquals('2022-07-18 09:00', $actual);
```

```
Failed asserting that two strings are equal.
- Expected | + Actual
@@ @@
-'2022-07-18 09:00'
+'2022-07-18 13:00'
```

**Comment by kylekatarnls** [comment]
`exceptions` means you replace the whole day. For instance you can have a typical Monday being 8AM to 7PM and having an exception for 2022-07-18 being only afternoon 2PM - 7PM or even being empty:

```php
'exceptions' => [
                '2022-07-18' => [
                    'hours' => [],
                ],
            ],
```

Most users use this to register holidays for instance.

If `exceptions` were added to normal week, it would not be possible to have an exception that does not include them on purpose and we would likely name it `add` or something conveying the idea it would be merged.

**Comment by c33s** [comment]
@kylekatarnls would you be against of having a flag for exceptions so that they would merge? the current behavior is quite unhandy if you want to add additional opening hours and would lead to quite some coding to check if an exception matches an opening day and if so to merge the time ranges.
should i open a new "feature request"-ticket or is this ticket ok?

**Comment by kylekatarnls** [comment]
Hello. Don't you think the code below is enough?
```php
$now = new Carbon('2022-07-17 14:01');
Carbon::setTestNow($now);
CarbonImmutable::setTestNow($now);

$normalWeek = [
    'monday' => ['09:00-12:00'],
];
$exceptions = [
    '2022-07-18' => [
        'hours' => \Spatie\OpeningHours\OpeningHours::mergeOverlappingRanges(
            [...($normalWeek['monday'] ?? []), '13:00-18:00'],
        ),
    ],
];

$openingHours = \Spatie\OpeningHours\OpeningHours::create([
    ...$normalWeek,
    'exceptions' => $exceptions,
]);
$actual = $openingHours->nextOpen($now)->format('Y-m-d H:i');

$this->assertEquals('2022-07-18 09:00', $actual);
```

(The call to `\Spatie\OpeningHours\OpeningHours::mergeOverlappingRanges` is only needed if you ranges can overlap, for instance if mondays has `'09:00-12:00'` and exception has `'11:00-16:00'` it will transform it into `09:00-16:00` time range.)

I would not add a boolean flag in order to respect the principle of single responsibility. I think "except" is the right verb for days excluded from the typical week.

And a global flag would force you to have either all merged or all using the current behavior while with not much more code the `[...($normalWeek['monday'] ?? []), '13:00-18:00']` gives you the ability to choose for each exception if it includes the normal days hours or even the hours coming from an other day.

So instead of a global boolean it could be a local key on each exception, or maybe (to respect the wording semantic) to have an other key, the the hours you merge with the rest are not at all in the `exceptions` array but in an other array (I don't have an idea for the name).

But else the code above sounds to me like quite reasonable and goes legitimately in the business app code. Generally we assume the role of this library is to answer questions about your opening hours schedule but crafting the schedule is the responsibility of the app.

Users of this library have very various ways to build the config array (using a DB, files, APIs, user input, etc.) and I'm not keen on bloating the library with methods that are in the end just array-builder helpers. Modern PHP now supports every array packing/unpacking, older version just need to rely on `array_merge`/`array_replace` instead, and `mergeOverlappingRanges` will cover the needs for time range merging already.

So I would approve some adding there only if it proves solving an actual problem and if it solve it in a generic way (e.g. have good chance to help other users with the similar issue).
