### ISSUE TITLE
Feature request: Recurring exceptions

### ISSUE THREAD

**Issue by mikemand** [spatie/opening-hours#20]
Some way to include recurring exceptions without having to add every occurrence to the `exceptions` array would be great. That way every Christmas (for example), past and present, could be marked as closed without ending up with entries every year.

Another option would be to allow exceptions to only have a month and day part, including or excluding the year as needed.

**Comment by sebastiandedeyne** [comment]
I'm partial about this one, because there will always be recurring exceptions that this package won't be able to handle (e.g. Thanksgiving and Easter don't have a fixed date).

I think I'd rather recommend adding the exceptions dynamically with you own business logic or a library like Yasumi.

https://github.com/azuyalabs/yasumi

**Comment by mikemand** [comment]
That package is pretty neat. I think that will work. Thank you!
