### ISSUE TITLE
Can it be used with relation to another model?

### ISSUE THREAD

**Issue by thenerdsinn** [spatie/opening-hours#60]
I mean in case of library or restaurant directory, where we have multiple entities that needs opening days and hours.

**Comment by sebastiandedeyne** [comment]
In the past, I've stored the openings hours array in a JSON column, so you can have different hours per record.

**Comment by desaintflorent** [comment]
Hi @sebastiandedeyne, 
i have a similar question. In my case I want to store opening hours of a model ( shops for example ). 
I understand that i could store it as a Json column of my model. But If I want to query all shops opened at a specific time, I will not be able to do that with a Json column right ? 
Do you have an idea in mind that would work with your plugin or should I consider going on a custom solution for this case, like a dedicated openingHours model ?

**Comment by kylekatarnls** [comment]
Hi @desaintflorent,

> I will not be able to do that with a Json column right ?

Not exactly right, it will be very slow to proceed but it's possible.

For that reason and many others I would recommend to everyone to never store any kind of serialization in your DB (JSON, serialize, var_export, lists with separator, etc.). Each cell of a table should always contain only 1 atomic data.

I would use a structure like this:

|column name|type|
|--|--|
|id|int|
|id_shop|int|
|day|tinyint|
|hour_start|tinyint|
|minute_start|tinyint|
|hour_end|tinyint|
|minute_end|tinyint|

With this table `opening_hours`, open shop at 11:35 on monday are shops having at least 1 row in `opening_hours` matching `day = 1 AND hour_start * 60 + minute_start <= 11 * 60 + 35 AND 11 * 60 + 35 < hour_end * 60 + minute_end`

**Comment by desaintflorent** [comment]
Ok thank's that's what I was thinking. I'm planning on doing something similar but instead of doing hours_start and minute_start will have a time_open ( and time_close ) column with 4 digits for hours and minutes. 
So I could look for shops that are open between  '1025' and '1200' for exemple.

**Comment by kylekatarnls** [comment]
@desaintflorent This will be more tricky with this storage if you want later to now for example in how many minutes a shop will open: 1200 - 1158 = 42 but of course, it's 2 minutes, not 42.

It's why storing data in a more atomic way is always safer for future maintenance. "1025" is laready composite data, not atomic. 625 (10 * 60 + 25) would be better because it represents minutes from the beginning of the day, it's a duration in only one unit. And still 1 column for hour and 1 column for minutes will be the best choice to make your future developments easier.
