### ISSUE TITLE
isOpenAt returns false (and isClosedAt returns true) for the last second of the day

### ISSUE THREAD

**Issue by ipeevski** [spatie/opening-hours#63]
I believe from a practical sense, the last second of the working day should be considered working time.

When connected to automated systems, if something is scheduled every hour, it should be accepted at the last hour too.

Code snippet to illustrate
```
$openingHours = OpeningHours::create([
    'monday' => ['09:00-18:00'],
    'tuesday' => ['09:00-18:00'],
    'wednesday' => ['09:00-18:00'],
    'thursday' => ['09:00-18:00'],
    'friday' => ['09:00-18:00'],
    'saturday' => ['09:00-18:00'],
    'sunday' => ['09:00-18:00']
]);

// Expected to return true, returns false
$openingHours->isOpenAt(new DateTime('2016-09-26 18:00:00'));
```

**Comment by kylekatarnls** [comment]
It's a bit specific (and it is a breaking change) so it seems right to me not having merged this. Still you can test it this way:

```php
function isOpenOrJustClosedAt($openingHoursForDay, $date) {
  return $openingHoursForDay->isOpenAt($date, (clone $date)->modify('-1 second'));
}

isOpenOrJustClosedAt($openingHoursForDay, new \DateTime('2016-09-26 18:00:00'));
```

**Comment by ipeevski** [comment]
While end time is open to interpretation (I would be interested to see what the majority would consider common - if the end time is inclusive or not), if the library is not modified to behave in the way that I believe is semantically correct (it is my opinion after all), then I think it would at least be prudent to include a mechanism to make it behave in such fashion (either via configuration or by including a method, such as the proposed one).

Also I would like to note that the proposed function would have undesirable results when start-time is concerned.

**Comment by kylekatarnls** [comment]
Supposing you want green cells for open hours in a table. Then the 18h should not be green. See, there are plenty of cases when an inclusive end will cause bugs. Some users could be tempted to wish an inclusive test which seems harmless but would be surprised by the consequences. You run into a particular case for you business usage. And what is semantically correct is to say that you run you script when the business is open or closed right now, not to say that close-time is nearly open and returning true, this is semantically cheating.

So I'm very not convicted the majority would support this change, then even if they would, it's a breaking change, it has big consequences that will break many existing applications.

PS: Can you precise "undesireable" because 9:00:00 is open when 8:59:59 is closed, that seems pretty expected to me.

**Comment by nfragnet** [comment]
> While end time is open to interpretation (I would be interested to see what the majority would consider common - if the end time is inclusive or not)

Personally I wouldn't even think about including the end time. 

Even if we talk about **opening** hours, the second part is not "the last minute of opening" but "the closing hour".

I never saw any business closing at 18:00:00 displaying the following

Monday: 09:00 - 17:59
Tuesday 09:00 - 17:59
Wednesday 09:00 - 17:59
...

**Comment by kylekatarnls** [comment]
This custom function should be enough for most cases: https://github.com/spatie/opening-hours/issues/63#issuecomment-434252512

**Comment by ipeevski** [comment]
Fair enough. Thank you all.
