### ISSUE TITLE
Looking for maintainer

### ISSUE THREAD

**Issue by freekmurze** [spatie/opening-hours#77]
We're looking for a maintainer that can help us answer to issues, review PRs and tag new releases.

If you have experience with open source in general and/or this package in particular, let me know: freek@spatie.be

**Comment by Jamesking56** [comment]
I'd be happy to, I'll send you an email :+1:

**Comment by freekmurze** [comment]
@Jamesking56 🎉

**Comment by bosunski** [comment]
Will send you an email too 😅

**Comment by rsm23** [comment]
Will do

**Comment by Jamesking56** [comment]
@freekmurze To allieviate you from this package, I am willing for my company @momentumstudi0 to take on this package in the form of a fork with a separate composer package `momentumstudio/opening-hours`.

Is this something that would be better for you and all the users of this package? With this one publishing as abandoned forwarding to `momentumstudio/opening-hours`?

**Comment by kylekatarnls** [comment]
Hi,

I maintain among others https://github.com/briannesbitt/Carbon and https://github.com/kylekatarnls/business-time (that use `spatie/opening-hours`)

Right now, `business-time` uses a work-around to fix #73, enable DateTimeImmutable and support wrappers such as Carbon.

Regarding commits and issues frequency, it does not seems `opening-hours` need big refactoring, so an ownership transfer seems not justified to me. I agree to help (answer/reviews/bug fixes/tag) but I would feel more confortable doing it on the original project than on a fork.

I will need #75 to drop the work-around on `business-time` but I would prefer to just update to `spatie/opening-hours` to `^2` than using an other project or fork it then get potential namespace conflict if different versions of the project would fall in the same project. We should really avoid to explode the project into multiple forks. First, because it seems faire to me `spatie` would keep the ownership on the project even if it's maintained by other developers. Then to keep a unique reference providing a consistent common support.

**Comment by freekmurze** [comment]
@Jamesking56 Thank you for your offer but we decided to pick @kylekatarnls as the maintainer.

@kylekatarnls Thank you for all the nice work you to at Carbon, we love that package at Spatie. 👍

I'll give you edit rights on this repo. Feel free to respond to issues, merge PRs and tag new releases. When you should want to tag a major new release, prepare it on a new branch, let us know, so we can review it.

 If you have any questions ping me or @sebastiandedeyne  (freekmurze and sebdedyne on Twitter).

Thank you for stepping up!

**Comment by sebastiandedeyne** [comment]
@kylekatarnls A huge thanks for helping out here!
