### ISSUE TITLE
Object of class DateTime could not be converted to string

### ISSUE THREAD

**Issue by edgren** [spatie/opening-hours#87]
Hi!

I can't use the `nextOpen()` nor `nextClose()` functions because PHP complains about `new DateTime()` not being a string:

`Recoverable fatal error: Object of class DateTime could not be converted to string in ...`

```PHP
$nextOpen = $openingHours->nextOpen(new DateTime('2019-01-07'));
echo $nextOpen;
```

Please fix!

**Comment by kylekatarnls** [comment]
The following test is successful:
https://github.com/spatie/opening-hours/blob/master/tests/OpeningHoursTest.php#L269

So I guess your `$openingHours` may not be a `OpeningHours` instance.

Please provide a minimal standalone code that I can run to reproduce the code.

**Comment by edgren** [comment]
Ok. Maybe it's because of how I call the class? If I call the class like you do in the test page, I get a "class not found" error. I used Composer to add your class to my project.

```PHP
require_once 'vendor/autoload.php';

$opening_hours = Spatie\OpeningHours\OpeningHours::create([
	'monday' => ['10:00-18:00'],
	'tuesday' => ['10:00-18:00'],
	'wednesday' => ['10:00-18:00'],
	'thursday' => ['10:00-18:00'],
	'friday' => ['10:00-18:00'],
	'saturday' => ['10:00-13:00'],
	'sunday' => [],
	'exceptions' => [
		# '2018-12-23' => ['10:00-18:00']
	]
]);

$nextTimeOpen = $openingHours->nextOpen(new DateTime('2016-09-26 12:00:00'));
echo $nextTimeOpen;
```

**Comment by kylekatarnls** [comment]
OK, understood, please pay attention to the line number of your error. The conversion is made by `echo` not by `nextOpen` because `$nextTimeOpen` is a `DateTime` instance and `DateTime` has no method `__toString` so it can't be casted to string, you can't `echo` a native `DateTime` object:

```php
<?php

require_once 'vendor/autoload.php';

$opening_hours = Spatie\OpeningHours\OpeningHours::create([
    'monday' => ['10:00-18:00'],
    'tuesday' => ['10:00-18:00'],
    'wednesday' => ['10:00-18:00'],
    'thursday' => ['10:00-18:00'],
    'friday' => ['10:00-18:00'],
    'saturday' => ['10:00-13:00'],
    'sunday' => [],
    'exceptions' => [
        # '2018-12-23' => ['10:00-18:00']
    ]
]);

$nextTimeOpen = $opening_hours->nextOpen(new DateTime('2016-09-26 12:00:00'));

echo $nextTimeOpen->format('Y-m-d H:i');
```

Be aware `nextOpen` will preserve the typing so if you pass an extended class having a string-cast, such as `Carbon`, then you can `echo` it directly.

About namespaces, you can use `Spatie\OpeningHours\OpeningHours` or having `use Spatie\OpeningHours\OpeningHours;` at the top of your file, then simply use `OpeningHours` in the code.

You may also be interested in:
https://github.com/kylekatarnls/business-time

Giving you the following code:

```php
<?php

use Carbon\Carbon;
use Cmixin\BusinessTime;

require_once 'vendor/autoload.php';

BusinessTime::enable(Carbon::class, [
    'monday' => ['10:00-18:00'],
    'tuesday' => ['10:00-18:00'],
    'wednesday' => ['10:00-18:00'],
    'thursday' => ['10:00-18:00'],
    'friday' => ['10:00-18:00'],
    'saturday' => ['10:00-13:00'],
    'sunday' => [],
    'exceptions' => [
        # '2018-12-23' => ['10:00-18:00']
    ]
]);

echo Carbon::parse('2016-09-26 12:00:00')->nextOpen();
```
